Adding .exe check

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -22,6 +22,15 @@ jobs:
       - name: Run BubbleScan script
         run: ./BubbleScan.sh
 
+      - name: Verify BubbleScan.exe exists
+        run: |
+          if [ -f "ServerCode/dist/BubbleScan.exe" ]; then
+            echo "BubbleScan.exe found."
+          else
+            echo "BubbleScan.exe not found in the expected directory."
+            exit 1
+          fi
+
       - name: Archive executable and static files
         run: zip -r ServerCode/dist/Bubblescan.zip ServerCode/dist/BubbleScan.exe ServerCode/dist/static
 
